apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks-api
spec:
  type: {{ .Values.deltask.type }}
  selector:
    app: {{ .Release.Name }}-todo-delete-tasks-api
  ports:
    - port: {{ .Values.deltask.port }}
      targetPort: {{ .Values.deltask.targetPort }}
      
