apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-add-tasks-api
spec:
  replicas: {{ .Values.addtask.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-add-tasks-api
  template:
    metadata:
      name: {{ .Release.Name }}-todo-add-tasks
      labels:
        app: {{ .Release.name }}-todo-add-tasks-api
    spec:
      containers:
      - name: {{ .Realease.name }}-todo-add-tasks-api
        image: {{ .Values.commom.acrname }}/{{ .Values.addtask.imagename }}:{{ .Values.addtask.version }}
        ports:
        - containerPort: {{ .Values.addtask.containerPort }}
        env: 
        - name: {{ .Values.commom.DBconnectionstring.name }}
          value: {{ .Values.common.DBconnectionstring.value }}