apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-ui
spec:
  replicas: {{ .values.todoUI.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-ui
  template:
    metadata:
      name: {{ .Release.Name }}-todo-ui
      labels:
        app: {{ .Release.Name }}-todo-ui
    spec:
      containers:
      - name: {{ .Release.Name }}-todo-ui
        image: {{ .Values.commomc.acrname }}/{{ .Values.todoUI.image.imagename }}:{{ .Values.todoUI.image.version }}
        ports:
        - containerPort: {{ .Values.todoUI.ports.containerPort }}