apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-todo-ui-ingress
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}
  rules:
  - host: {{ .Values.todoUI.host }}
    http:
      paths:
      - pathType: {{ .Values.todoUI.pathType }}
        path: {{ .Values.todoUI.path }}
        backend:
          service:
            name: {{ .Release.Name }}-todo-ui
            port: 
              number: {{ .Values.todoUI.number }}
